name: Trigger Jenkins Build

on:
  push:
    branches:
      - master 

jobs:
  trigger-jenkins:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST "$JENKINS_URL/job/TriggerJenkinsBuild/build" \
               --user "$JENKINS_USER:$JENKINS_API_TOKEN"
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}

